@TestApi_HostAddress = http://localhost:5148

GET {{TestApi_HostAddress}}/api/Persons
Accept: application/json

###
POST {{TestApi_HostAddress}}/api/Persons
Accept: application/json
Content-Type: application/json

{
    "id": "b8e4b367-3b4a-4f47-8c9c-5f4c0f9b0c65",
    "name": "Macavi",
    "age": 32,
    "gender": "Female"
}

###
DELETE {{TestApi_HostAddress}}/api/Persons/b8e4b367-3b4a-4f47-8c9c-5f4c0f9b0c65

###
PUT {{TestApi_HostAddress}}/api/Persons/b8e4b367-3b4a-4f47-8c9c-5f4c0f9b0c65
Content-Type: application/json

{
    "id": "b8e4b367-3b4a-4f47-8c9c-5f4c0f9b0c65",
    "name": "Macavelli",
    "age": 32,
    "gender": "male"
}

